version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: locadora-veiculos
      MYSQL_RANDOM_ROOT_PASSWORD: true
    ports:
      - "3306:3306"
    volumes:
      - C:/Users/renat/Documentos:/var/lib/mysql